server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
    #配置一个文字的模板ID
    token: asdqwe123
    singleTemplateId: oXBUq606Aq5COxAOuXueM7Ju2ZLY
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: XF16jqXBYkvF-kwM2-QnXsSRhL4lQo65lCiMbcuXEuk	
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 早上好呀呀鸭
            #你们的相遇时间
            meetDate: '2021-12-14'
            city: 北京
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 110000
            constellation: 双子座
          #把‘填写你的需要特定配置的微信用户号’覆盖位微信用户ID，可以对照正确填写好的配置示例，多用户可以按照格式继续添加下去
          oXBUq606Aq5COxAOuXueM7Ju2ZLY:
            title: 早上好呀呀鸭
            meetDate: '2021-12-14'
            city: 北京
            cityCode: 110000
            constellation: 狮子座
      #颜文字模板
      emoticonsTemplate:XF16jqXBYkvF-kwM2-QnXsSRhL4lQo65lCiMbcuXEuk
        templateId: 填写模板ID
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1
#发送者个人信息
personal:
  info:
    constellation: 水瓶座

